### ISSUE TITLE
Don't zip resources and scripts in releases

### ISSUE THREAD

**Issue by DasSkelett** [evandisoft/RedOnion#28]
I am currently trying to create a netkan file in order to add RedOnion to CKAN.

Problem is, that CKAN can't extract zip folders inside the main (root) zip.
Also, as far as I know, zipping inside another zip doesn't reduce the total size more than a "single" compression.

Thanks alot.

**Comment by evandisoft** [comment]
Thanks. I will have to discuss this with the other maintainer.

**Comment by evandisoft** [comment]
WE don't need the contents of those folders extracted by ckan.

**Comment by firdacz** [comment]
@DasSkelett And what is the problem really? We do not expect those zips be extracted, on the contrary! Those zips (Resources.zip and Scripts.zip) are there to provide fallback if the file is not found. That is to allow users to override both the resources and our scripts. Especially helpful for the scripts as useres are expected to modify our scripts (just by loading it in the REPL and saving the modified version creates the overriding file).

**Comment by DasSkelett** [comment]
Oh, I thought the Resources folder was necessary for the mod to work, but I might have misunderstood.
Thanks for the clarification.
